# Predict which customers will leave(churn)

[Data Source](https://github.com/IBM/telco-customer-churn-on-icp4d/blob/master/data/Telco-Customer-Churn.csv#L7044)

In [67]:
import tensorflow as tf 
import numpy as np 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
import pandas as pd

### **Loading data**

In [68]:
df=pd.read_csv('data\Telco-Customer-Churn.csv')

In [69]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [70]:
rows,columns =df.shape
print(f"{rows} and {columns} columns")

7043 and 21 columns

In [71]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [72]:
df.isnull().sum()/len(df)*100

customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
Contract            0.0
PaperlessBilling    0.0
PaymentMethod       0.0
MonthlyCharges      0.0
TotalCharges        0.0
Churn               0.0
dtype: float64

In [73]:
values = df["TotalCharges"].unique() 
for index, value in enumerate(values):
    if value == ' ':
        print(index)
        break 
    print(f"{index}: VALUE: {value}: converted values => {float(value)}")

0: VALUE: 29.85: converted values => 29.85
1: VALUE: 1889.5: converted values => 1889.5
2: VALUE: 108.15: converted values => 108.15
3: VALUE: 1840.75: converted values => 1840.75
4: VALUE: 151.65: converted values => 151.65
5: VALUE: 820.5: converted values => 820.5
6: VALUE: 1949.4: converted values => 1949.4
7: VALUE: 301.9: converted values => 301.9
8: VALUE: 3046.05: converted values => 3046.05
9: VALUE: 3487.95: converted values => 3487.95
10: VALUE: 587.45: converted values => 587.45
11: VALUE: 326.8: converted values => 326.8
12: VALUE: 5681.1: converted values => 5681.1
13: VALUE: 5036.3: converted values => 5036.3
14: VALUE: 2686.05: converted values => 2686.05
15: VALUE: 7895.15: converted values => 7895.15
16: VALUE: 1022.95: converted values => 1022.95
17: VALUE: 7382.25: converted values => 7382.25
18: VALUE: 528.35: converted values => 528.35
19: VALUE: 1862.9: converted values => 1862.9
20: VALUE: 39.65: converted values => 39.65
21: VALUE: 202.25: converted values => 202.25
22: VALUE: 20.15: converted values => 20.15
23: VALUE: 3505.1: converted values => 3505.1
24: VALUE: 2970.3: converted values => 2970.3
25: VALUE: 1530.6: converted values => 1530.6
26: VALUE: 4749.15: converted values => 4749.15
27: VALUE: 30.2: converted values => 30.2
28: VALUE: 6369.45: converted values => 6369.45
29: VALUE: 1093.1: converted values => 1093.1
30: VALUE: 6766.95: converted values => 6766.95
31: VALUE: 181.65: converted values => 181.65
32: VALUE: 1874.45: converted values => 1874.45
33: VALUE: 20.2: converted values => 20.2
34: VALUE: 45.25: converted values => 45.25
35: VALUE: 7251.7: converted values => 7251.7
36: VALUE: 316.9: converted values => 316.9
37: VALUE: 3548.3: converted values => 3548.3
38: VALUE: 3549.25: converted values => 3549.25
39: VALUE: 1105.4: converted values => 1105.4
40: VALUE: 475.7: converted values => 475.7
41: VALUE: 4872.35: converted values => 4872.35
42: VALUE: 418.25: converted values => 418.25
43: VALUE: 4861.45: converted values => 4861.45
44: VALUE: 981.45: converted values => 981.45
45: VALUE: 3906.7: converted values => 3906.7
46: VALUE: 97: converted values => 97.0
47: VALUE: 144.15: converted values => 144.15
48: VALUE: 4217.8: converted values => 4217.8
49: VALUE: 4254.1: converted values => 4254.1
50: VALUE: 3838.75: converted values => 3838.75
51: VALUE: 1426.4: converted values => 1426.4
52: VALUE: 1752.65: converted values => 1752.65
53: VALUE: 633.3: converted values => 633.3
54: VALUE: 4456.35: converted values => 4456.35
55: VALUE: 1752.55: converted values => 1752.55
56: VALUE: 6311.2: converted values => 6311.2
57: VALUE: 7076.35: converted values => 7076.35
58: VALUE: 894.3: converted values => 894.3
59: VALUE: 7853.7: converted values => 7853.7
60: VALUE: 4707.1: converted values => 4707.1
61: VALUE: 5450.7: converted values => 5450.7
62: VALUE: 2962: converted values => 2962.0
63: VALUE: 957.1: converted values => 957.1
64: VALUE: 857.25: converted values => 857.25
65: VALUE: 244.1: converted values => 244.1
66: VALUE: 3650.35: converted values => 3650.35
67: VALUE: 2497.2: converted values => 2497.2
68: VALUE: 930.9: converted values => 930.9
69: VALUE: 887.35: converted values => 887.35
70: VALUE: 49.05: converted values => 49.05
71: VALUE: 1090.65: converted values => 1090.65
72: VALUE: 7099: converted values => 7099.0
73: VALUE: 1424.6: converted values => 1424.6
74: VALUE: 177.4: converted values => 177.4
75: VALUE: 6139.5: converted values => 6139.5
76: VALUE: 2688.85: converted values => 2688.85
77: VALUE: 482.25: converted values => 482.25
78: VALUE: 2111.3: converted values => 2111.3
79: VALUE: 1216.6: converted values => 1216.6
80: VALUE: 79.35: converted values => 79.35
81: VALUE: 565.35: converted values => 565.35
82: VALUE: 496.9: converted values => 496.9
83: VALUE: 4327.5: converted values => 4327.5
84: VALUE: 973.35: converted values => 973.35
85: VALUE: 918.75: converted values => 918.75
86: VALUE: 2215.45: converted values => 2215.45
87: VALUE: 1057: converted values => 1057.0
88: VALUE: 927.1: converted values => 927.1
89: VALUE: 1009.25: converted values => 1009.25
90: VALUE: 2570.2: converted values => 2570.2
91: VALUE: 74.7: converted values => 74.7
92: VALUE: 5714.25: converted values => 5714.25
93: VALUE: 7107: converted values => 7107.0
94: VALUE: 7459.05: converted values => 7459.05
95: VALUE: 927.35: converted values => 927.35
96: VALUE: 4748.7: converted values => 4748.7
97: VALUE: 113.85: converted values => 113.85
98: VALUE: 1107.2: converted values => 1107.2
99: VALUE: 2514.5: converted values => 2514.5
100: VALUE: 19.45: converted values => 19.45
101: VALUE: 3605.6: converted values => 3605.6
102: VALUE: 3027.25: converted values => 3027.25
103: VALUE: 7611.85: converted values => 7611.85
104: VALUE: 100.2: converted values => 100.2
105: VALUE: 7303.05: converted values => 7303.05
106: VALUE: 927.65: converted values => 927.65
107: VALUE: 3921.3: converted values => 3921.3
108: VALUE: 1363.25: converted values => 1363.25
109: VALUE: 5238.9: converted values => 5238.9
110: VALUE: 3042.25: converted values => 3042.25
111: VALUE: 3954.1: converted values => 3954.1
112: VALUE: 2868.15: converted values => 2868.15
113: VALUE: 3423.5: converted values => 3423.5
114: VALUE: 248.4: converted values => 248.4
115: VALUE: 1126.35: converted values => 1126.35
116: VALUE: 1064.65: converted values => 1064.65
117: VALUE: 835.15: converted values => 835.15
118: VALUE: 2151.6: converted values => 2151.6
119: VALUE: 5515.45: converted values => 5515.45
120: VALUE: 112.75: converted values => 112.75
121: VALUE: 229.55: converted values => 229.55
122: VALUE: 350.35: converted values => 350.35
123: VALUE: 62.9: converted values => 62.9
124: VALUE: 3027.65: converted values => 3027.65
125: VALUE: 2135.5: converted values => 2135.5
126: VALUE: 1723.95: converted values => 1723.95
127: VALUE: 19.75: converted values => 19.75
128: VALUE: 3985.35: converted values => 3985.35
129: VALUE: 1215.65: converted values => 1215.65
130: VALUE: 1502.65: converted values => 1502.65
131: VALUE: 3260.1: converted values => 3260.1
132: VALUE: 35.45: converted values => 35.45
133: VALUE: 81.25: converted values => 81.25
134: VALUE: 1188.2: converted values => 1188.2
135: VALUE: 1778.5: converted values => 1778.5
136: VALUE: 1277.75: converted values => 1277.75
137: VALUE: 1170.55: converted values => 1170.55
138: VALUE: 70.45: converted values => 70.45
139: VALUE: 6425.65: converted values => 6425.65
140: VALUE: 563.65: converted values => 563.65
141: VALUE: 5971.25: converted values => 5971.25
142: VALUE: 5289.05: converted values => 5289.05
143: VALUE: 1756.2: converted values => 1756.2
144: VALUE: 6416.7: converted values => 6416.7
145: VALUE: 61.35: converted values => 61.35
146: VALUE: 45.65: converted values => 45.65
147: VALUE: 1929.95: converted values => 1929.95
148: VALUE: 1071.4: converted values => 1071.4
149: VALUE: 564.35: converted values => 564.35
150: VALUE: 655.5: converted values => 655.5
151: VALUE: 7930.55: converted values => 7930.55
152: VALUE: 5215.25: converted values => 5215.25
153: VALUE: 113.5: converted values => 113.5
154: VALUE: 1152.8: converted values => 1152.8
155: VALUE: 1821.95: converted values => 1821.95
156: VALUE: 419.9: converted values => 419.9
157: VALUE: 1024: converted values => 1024.0
158: VALUE: 251.6: converted values => 251.6
159: VALUE: 764.55: converted values => 764.55
160: VALUE: 1592.35: converted values => 1592.35
161: VALUE: 135.2: converted values => 135.2
162: VALUE: 3958.25: converted values => 3958.25
163: VALUE: 233.9: converted values => 233.9
164: VALUE: 1363.45: converted values => 1363.45
165: VALUE: 273: converted values => 273.0
166: VALUE: 6254.45: converted values => 6254.45
167: VALUE: 2651.2: converted values => 2651.2
168: VALUE: 321.4: converted values => 321.4
169: VALUE: 3539.25: converted values => 3539.25
170: VALUE: 242.8: converted values => 242.8
171: VALUE: 1181.75: converted values => 1181.75
172: VALUE: 5000.2: converted values => 5000.2
173: VALUE: 654.55: converted values => 654.55
174: VALUE: 780.2: converted values => 780.2
175: VALUE: 1145.7: converted values => 1145.7
176: VALUE: 503.6: converted values => 503.6
177: VALUE: 1559.25: converted values => 1559.25
178: VALUE: 1252: converted values => 1252.0
179: VALUE: 29.95: converted values => 29.95
180: VALUE: 45.3: converted values => 45.3
181: VALUE: 662.65: converted values => 662.65
182: VALUE: 2453.3: converted values => 2453.3
183: VALUE: 1111.65: converted values => 1111.65
184: VALUE: 24.8: converted values => 24.8
185: VALUE: 1023.85: converted values => 1023.85
186: VALUE: 82.15: converted values => 82.15
187: VALUE: 244.8: converted values => 244.8
188: VALUE: 2379.1: converted values => 2379.1
189: VALUE: 3173.35: converted values => 3173.35
190: VALUE: 531: converted values => 531.0
191: VALUE: 1375.4: converted values => 1375.4
192: VALUE: 8129.3: converted values => 8129.3
193: VALUE: 1192.7: converted values => 1192.7
194: VALUE: 1901.65: converted values => 1901.65
195: VALUE: 587.4: converted values => 587.4
196: VALUE: 6519.75: converted values => 6519.75
197: VALUE: 8041.65: converted values => 8041.65
198: VALUE: 20.75: converted values => 20.75
199: VALUE: 2681.15: converted values => 2681.15
200: VALUE: 1112.3: converted values => 1112.3
201: VALUE: 7405.5: converted values => 7405.5
202: VALUE: 1033.95: converted values => 1033.95
203: VALUE: 2958.95: converted values => 2958.95
204: VALUE: 2684.85: converted values => 2684.85
205: VALUE: 4179.2: converted values => 4179.2
206: VALUE: 79.9: converted values => 79.9
207: VALUE: 1934.45: converted values => 1934.45
208: VALUE: 6654.1: converted values => 6654.1
209: VALUE: 84.5: converted values => 84.5
210: VALUE: 25.25: converted values => 25.25
211: VALUE: 1124.2: converted values => 1124.2
212: VALUE: 540.05: converted values => 540.05
213: VALUE: 1975.85: converted values => 1975.85
214: VALUE: 3437.45: converted values => 3437.45
215: VALUE: 3139.8: converted values => 3139.8
216: VALUE: 3789.2: converted values => 3789.2
217: VALUE: 5324.5: converted values => 5324.5
218: VALUE: 624.6: converted values => 624.6
219: VALUE: 268.35: converted values => 268.35
220: VALUE: 1836.9: converted values => 1836.9
221: VALUE: 179.35: converted values => 179.35
222: VALUE: 219.35: converted values => 219.35
223: VALUE: 1288.75: converted values => 1288.75
224: VALUE: 2545.75: converted values => 2545.75
225: VALUE: 55.2: converted values => 55.2
226: VALUE: 2723.15: converted values => 2723.15
227: VALUE: 4107.25: converted values => 4107.25
228: VALUE: 5760.65: converted values => 5760.65
229: VALUE: 4747.5: converted values => 4747.5
230: VALUE: 84.6: converted values => 84.6
231: VALUE: 1566.9: converted values => 1566.9
232: VALUE: 702: converted values => 702.0
233: VALUE: 114.1: converted values => 114.1
234: VALUE: 299.05: converted values => 299.05
235: VALUE: 1305.95: converted values => 1305.95
236: VALUE: 1120.3: converted values => 1120.3
237: VALUE: 284.35: converted values => 284.35
238: VALUE: 6350.5: converted values => 6350.5
239: VALUE: 7878.3: converted values => 7878.3
240: VALUE: 3187.65: converted values => 3187.65
241: VALUE: 6126.15: converted values => 6126.15
242: VALUE: 731.3: converted values => 731.3
243: VALUE: 273.4: converted values => 273.4
244: VALUE: 2531.8: converted values => 2531.8
245: VALUE: 1074.3: converted values => 1074.3
246: VALUE: 48.55: converted values => 48.55
247: VALUE: 4298.45: converted values => 4298.45
248: VALUE: 4619.55: converted values => 4619.55
249: VALUE: 147.15: converted values => 147.15
250: VALUE: 40.2: converted values => 40.2
251: VALUE: 2633.3: converted values => 2633.3
252: VALUE: 193.05: converted values => 193.05
253: VALUE: 4103.9: converted values => 4103.9
254: VALUE: 7008.15: converted values => 7008.15
255: VALUE: 5791.1: converted values => 5791.1
256: VALUE: 80.55: converted values => 80.55
257: VALUE: 1228.65: converted values => 1228.65
258: VALUE: 132.2: converted values => 132.2
259: VALUE: 1364.3: converted values => 1364.3
260: VALUE: 4925.35: converted values => 4925.35
261: VALUE: 1520.1: converted values => 1520.1
262: VALUE: 5032.25: converted values => 5032.25
263: VALUE: 5526.75: converted values => 5526.75
264: VALUE: 1195.25: converted values => 1195.25
265: VALUE: 2007.25: converted values => 2007.25
266: VALUE: 1099.6: converted values => 1099.6
267: VALUE: 1732.95: converted values => 1732.95
268: VALUE: 1511.2: converted values => 1511.2
269: VALUE: 3450.15: converted values => 3450.15
270: VALUE: 2172.05: converted values => 2172.05
271: VALUE: 70.6: converted values => 70.6
272: VALUE: 401.1: converted values => 401.1
273: VALUE: 5624.85: converted values => 5624.85
274: VALUE: 1339.8: converted values => 1339.8
275: VALUE: 771.95: converted values => 771.95
276: VALUE: 244.75: converted values => 244.75
277: VALUE: 322.9: converted values => 322.9
278: VALUE: 498.25: converted values => 498.25
279: VALUE: 25.4: converted values => 25.4
280: VALUE: 3687.75: converted values => 3687.75
281: VALUE: 1779.95: converted values => 1779.95
282: VALUE: 1783.6: converted values => 1783.6
283: VALUE: 927.15: converted values => 927.15
284: VALUE: 70: converted values => 70.0
285: VALUE: 606.55: converted values => 606.55
286: VALUE: 435.4: converted values => 435.4
287: VALUE: 1712.7: converted values => 1712.7
288: VALUE: 2021.2: converted values => 2021.2
289: VALUE: 1940.8: converted values => 1940.8
290: VALUE: 567.8: converted values => 567.8
291: VALUE: 220.35: converted values => 220.35
292: VALUE: 20.25: converted values => 20.25
293: VALUE: 5436.45: converted values => 5436.45
294: VALUE: 3437.5: converted values => 3437.5
295: VALUE: 3015.75: converted values => 3015.75
296: VALUE: 73.6: converted values => 73.6
297: VALUE: 1509.8: converted values => 1509.8
298: VALUE: 396.1: converted values => 396.1
299: VALUE: 356.65: converted values => 356.65
300: VALUE: 4109: converted values => 4109.0
301: VALUE: 3141.7: converted values => 3141.7
302: VALUE: 1229.1: converted values => 1229.1
303: VALUE: 2303.35: converted values => 2303.35
304: VALUE: 2054.4: converted values => 2054.4
305: VALUE: 3741.85: converted values => 3741.85
306: VALUE: 3682.45: converted values => 3682.45
307: VALUE: 19.25: converted values => 19.25
308: VALUE: 1886.25: converted values => 1886.25
309: VALUE: 4895.1: converted values => 4895.1
310: VALUE: 341.6: converted values => 341.6
311: VALUE: 415.55: converted values => 415.55
312: VALUE: 5686.4: converted values => 5686.4
313: VALUE: 1355.1: converted values => 1355.1
314: VALUE: 3058.65: converted values => 3058.65
315: VALUE: 2231.05: converted values => 2231.05
316: VALUE: 3236.35: converted values => 3236.35
317: VALUE: 4350.1: converted values => 4350.1
318: VALUE: 4264: converted values => 4264.0
319: VALUE: 44.8: converted values => 44.8
320: VALUE: 422.3: converted values => 422.3
321: VALUE: 4176.7: converted values => 4176.7
322: VALUE: 5138.1: converted values => 5138.1
323: VALUE: 880.05: converted values => 880.05
324: VALUE: 139.05: converted values => 139.05
325: VALUE: 973.65: converted values => 973.65
326: VALUE: 1470.05: converted values => 1470.05
327: VALUE: 739.35: converted values => 739.35
328: VALUE: 161.95: converted values => 161.95
329: VALUE: 4422.95: converted values => 4422.95
330: VALUE: 511.25: converted values => 511.25
331: VALUE: 155.8: converted values => 155.8
332: VALUE: 5293.95: converted values => 5293.95
333: VALUE: 4759.85: converted values => 4759.85
334: VALUE: 6148.45: converted values => 6148.45
335: VALUE: 3565.65: converted values => 3565.65
336: VALUE: 6603: converted values => 6603.0
337: VALUE: 1830.1: converted values => 1830.1
338: VALUE: 6223.8: converted values => 6223.8
339: VALUE: 4508.65: converted values => 4508.65
340: VALUE: 1328.15: converted values => 1328.15
341: VALUE: 865: converted values => 865.0
342: VALUE: 72.1: converted values => 72.1
343: VALUE: 168.2: converted values => 168.2
344: VALUE: 1303.5: converted values => 1303.5
345: VALUE: 996.85: converted values => 996.85
346: VALUE: 6430.9: converted values => 6430.9
347: VALUE: 2278.75: converted values => 2278.75
348: VALUE: 681.4: converted values => 681.4
349: VALUE: 574.35: converted values => 574.35
350: VALUE: 371.9: converted values => 371.9
351: VALUE: 840.1: converted values => 840.1
352: VALUE: 846: converted values => 846.0
353: VALUE: 889: converted values => 889.0
354: VALUE: 6823.4: converted values => 6823.4
355: VALUE: 805.1: converted values => 805.1
356: VALUE: 4016.75: converted values => 4016.75
357: VALUE: 83.75: converted values => 83.75
358: VALUE: 3959.15: converted values => 3959.15
359: VALUE: 2878.55: converted values => 2878.55
360: VALUE: 945.7: converted values => 945.7
361: VALUE: 1373.05: converted values => 1373.05
362: VALUE: 492.55: converted values => 492.55
363: VALUE: 1406: converted values => 1406.0
364: VALUE: 19.15: converted values => 19.15
365: VALUE: 6962.85: converted values => 6962.85
366: VALUE: 8126.65: converted values => 8126.65
367: VALUE: 690.25: converted values => 690.25
368: VALUE: 181.5: converted values => 181.5
369: VALUE: 830.8: converted values => 830.8
370: VALUE: 5608.4: converted values => 5608.4
371: VALUE: 3646.8: converted values => 3646.8
372: VALUE: 3662.25: converted values => 3662.25
373: VALUE: 25.35: converted values => 25.35
374: VALUE: 2566.5: converted values => 2566.5
375: VALUE: 5308.7: converted values => 5308.7
376: VALUE: 1410.25: converted values => 1410.25
377: VALUE: 3339.05: converted values => 3339.05
378: VALUE: 50.65: converted values => 50.65
379: VALUE: 4732.35: converted values => 4732.35
380: VALUE: 90.85: converted values => 90.85
381: VALUE: 5067.45: converted values => 5067.45
382: VALUE: 214.75: converted values => 214.75
383: VALUE: 4874.7: converted values => 4874.7
384: VALUE: 2348.45: converted values => 2348.45
385: VALUE: 4063: converted values => 4063.0
386: VALUE: 44: converted values => 44.0
387: VALUE: 2595.25: converted values => 2595.25
388: VALUE: 2309.55: converted values => 2309.55
389: VALUE: 89.3: converted values => 89.3
390: VALUE: 367.55: converted values => 367.55
391: VALUE: 3944.5: converted values => 3944.5
392: VALUE: 5965.95: converted values => 5965.95
393: VALUE: 3694.7: converted values => 3694.7
394: VALUE: 2524.45: converted values => 2524.45
395: VALUE: 1803.7: converted values => 1803.7
396: VALUE: 415.1: converted values => 415.1
397: VALUE: 624.15: converted values => 624.15
398: VALUE: 237.7: converted values => 237.7
399: VALUE: 7007.6: converted values => 7007.6
400: VALUE: 3848.8: converted values => 3848.8
401: VALUE: 419.4: converted values => 419.4
402: VALUE: 1468.75: converted values => 1468.75
403: VALUE: 5812: converted values => 5812.0
404: VALUE: 2861.45: converted values => 2861.45
405: VALUE: 19.9: converted values => 19.9
406: VALUE: 19.6: converted values => 19.6
407: VALUE: 233.7: converted values => 233.7
408: VALUE: 1066.15: converted values => 1066.15
409: VALUE: 2149.05: converted values => 2149.05
410: VALUE: 4473: converted values => 4473.0
411: VALUE: 3545.05: converted values => 3545.05
412: VALUE: 1195.75: converted values => 1195.75
413: VALUE: 6858.9: converted values => 6858.9
414: VALUE: 1024.7: converted values => 1024.7
415: VALUE: 1845.9: converted values => 1845.9
416: VALUE: 75.3: converted values => 75.3
417: VALUE: 132.25: converted values => 132.25
418: VALUE: 515.45: converted values => 515.45
419: VALUE: 2830.45: converted values => 2830.45
420: VALUE: 1110.5: converted values => 1110.5
421: VALUE: 449.3: converted values => 449.3
422: VALUE: 2838.55: converted values => 2838.55
423: VALUE: 5376.4: converted values => 5376.4
424: VALUE: 858.6: converted values => 858.6
425: VALUE: 1395.05: converted values => 1395.05
426: VALUE: 3975.7: converted values => 3975.7
427: VALUE: 1182.55: converted values => 1182.55

#### **Descent cleaning**

In [74]:
df_2 = df

In [75]:
df_2["TotalCharges"] = pd.to_numeric(df_2["TotalCharges"], errors="coerce") # coerce basically enable the alg. to be able to replace what cannot be changed into numerical with NaN (not a number)

In [76]:
df_2.iloc[470: 500][["customerID","TotalCharges"]]

     customerID  TotalCharges
470  4933-IKULF        330.60
471  3583-EKAPL         55.00
472  1304-BCCFO        564.40
473  4104-PVRPS       1315.35
474  9399-APLBT         74.70
475  2359-KMGLI       1861.50
476  3780-DDGSE       2747.20
477  4431-EDMIQ        554.05
478  0306-JAELE        453.40
479  6227-HWPWX        994.80
480  0486-LGCCH        225.75
481  0447-BEMNG       2145.00
482  4612-SSVHJ       1671.60
483  5168-MQQCA       8003.80
484  5949-XIKAE        680.05
485  7971-HLVXI       6130.85
486  9094-AZPHK       1415.00
487  3649-JPUGY       6201.95
488  4472-LVYGI           NaN
489  8372-JUXUI         74.35
490  3552-CTCYF       6597.25
491  6778-YSNIH        114.15
492  0388-EOPEX        139.40
493  5756-OZRIO       3902.60
494  6579-JPICP         20.40
495  8205-OTCHB        903.60
496  4134-BSXLX       1785.65
497  0505-SPOOW       1397.65
498  6235-VDHOM        131.05
499  7783-YKGDV       1238.45

In [77]:
df_2.iloc[488]

customerID                         4472-LVYGI
gender                                 Female
SeniorCitizen                               0
Partner                                   Yes
Dependents                                Yes
tenure                                      0
PhoneService                               No
MultipleLines                No phone service
InternetService                           DSL
OnlineSecurity                            Yes
OnlineBackup                               No
DeviceProtection                          Yes
TechSupport                               Yes
StreamingTV                               Yes
StreamingMovies                            No
Contract                             Two year
PaperlessBilling                          Yes
PaymentMethod       Bank transfer (automatic)
MonthlyCharges                          52.55
TotalCharges                              NaN
Churn                                      No
Name: 488, dtype: object

In [78]:
df_2 = df_2.drop(columns =["customerID"]) # we drop the customer id

In [79]:
df_2.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [80]:
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [81]:
df_2 = df_2.dropna() # we drop the rows with NaN values

In [82]:
df_2.dtypes

gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [83]:
df_2=pd.get_dummies(df_2,drop_first=True) # we convert the categorical variables into numerical variables

In [84]:
df_2.dtypes

SeniorCitizen                              int64
tenure                                     int64
MonthlyCharges                           float64
TotalCharges                             float64
gender_Male                                 bool
Partner_Yes                                 bool
Dependents_Yes                              bool
PhoneService_Yes                            bool
MultipleLines_No phone service              bool
MultipleLines_Yes                           bool
InternetService_Fiber optic                 bool
InternetService_No                          bool
OnlineSecurity_No internet service          bool
OnlineSecurity_Yes                          bool
OnlineBackup_No internet service            bool
OnlineBackup_Yes                            bool
DeviceProtection_No internet service        bool
DeviceProtection_Yes                        bool
TechSupport_No internet service             bool
TechSupport_Yes                             bool
StreamingTV_No internet service             bool
StreamingTV_Yes                             bool
StreamingMovies_No internet service         bool
StreamingMovies_Yes                         bool
Contract_One year                           bool
Contract_Two year                           bool
PaperlessBilling_Yes                        bool
PaymentMethod_Credit card (automatic)       bool
PaymentMethod_Electronic check              bool
PaymentMethod_Mailed check                  bool
Churn_Yes                                   bool
dtype: object

In [85]:
df_2["Churn_Yes"].value_counts()

Churn_Yes
False    5163
True     1869
Name: count, dtype: int64

In [86]:
df_2["Churn"]= (df_2["Churn_Yes"] == 1).astype(int) # we create a new column called churn which is equal to 1 if the customer has churned and 0 if the customer has not churned

In [87]:
df_2["Churn"].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [88]:
X =df_2.drop(columns="Churn").values.astype("float32") # we drop the churn column from the dataset and store it in X
y = df_2["Churn"].values
X, y

(array([[  0.  ,   1.  ,  29.85, ...,   1.  ,   0.  ,   0.  ],
        [  0.  ,  34.  ,  56.95, ...,   0.  ,   1.  ,   0.  ],
        [  0.  ,   2.  ,  53.85, ...,   0.  ,   1.  ,   1.  ],
        ...,
        [  0.  ,  11.  ,  29.6 , ...,   1.  ,   0.  ,   0.  ],
        [  1.  ,   4.  ,  74.4 , ...,   0.  ,   1.  ,   1.  ],
        [  0.  ,  66.  , 105.65, ...,   0.  ,   0.  ,   0.  ]],
       shape=(7032, 31), dtype=float32),
 array([0, 0, 1, ..., 0, 1, 0], shape=(7032,)))

#### **Split then scale the data**

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,stratify=y,random_state=42)

In [90]:
scaler = StandardScaler() # we create an instance of the StandardScaler class
scaler.fit(X_train) # we fit the scaler to the training data
X_train,X_test = scaler.transform(X_train), scaler.transform(X_test)# we transform the training data

In [91]:
X_train

array([[-0.4405457 , -0.833469  ,  0.44474947, ...,  1.3986266 ,
        -0.5367909 ,  1.6622266 ],
       [-0.4405457 , -0.508058  , -1.4921349 , ..., -0.71498716,
         1.8629229 , -0.60160273],
       [-0.4405457 , -1.2402327 , -0.12045064, ..., -0.71498716,
        -0.5367909 , -0.60160273],
       ...,
       [-0.4405457 ,  0.14276391,  0.92731786, ..., -0.71498716,
        -0.5367909 , -0.60160273],
       [-0.4405457 , -0.91482174,  0.03489676, ..., -0.71498716,
         1.8629229 , -0.60160273],
       [-0.4405457 , -1.2809091 , -1.3235666 , ..., -0.71498716,
        -0.5367909 ,  1.6622266 ]], shape=(4922, 31), dtype=float32)

## **Modelling**

In [92]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Input((X_train.shape[1],)), #  data is already flat hence we do not need to flatten the features trsnalte into an input

  # This is your first hidden layer n 128 neurons
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dropout(0.3),# 20% of your data is left out to lower the chance pof overfittinhs

  # This is your first hidden layer n 64 neurons
  tf.keras.layers.Dense(16, activation='relu'),
  tf.keras.layers.Dropout(0.3),# 20% of your data is left out to lower the chance pof overfittinh
  
  tf.keras.layers.Dense(10, activation='softmax')
])

In [93]:

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

In [94]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [95]:
model.fit(X_train, y_train, epochs=30)

Epoch 1/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5297 - loss: 1.4900
Epoch 2/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8570 - loss: 0.4474
Epoch 3/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9482 - loss: 0.1649
Epoch 4/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9762 - loss: 0.0811
Epoch 5/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9898 - loss: 0.0426
Epoch 6/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9925 - loss: 0.0298
Epoch 7/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9943 - loss: 0.0207
Epoch 8/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9959 - loss: 0.0142
Epoch 9/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9972 - loss: 0.0115
Epoch 10/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9976 - loss: 0.0100
Epoch 11/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9986 - loss: 0.0070
Epoch 12/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9980 - loss: 0.0066
Epoch 13/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9982 - loss: 0.0075
Epoch 14/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9992 - loss: 0.0043
Epoch 15/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9986 - loss: 0.0041
Epoch 16/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9986 - loss: 0.0051
Epoch 17/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9988 - loss: 0.0046
Epoch 18/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0025
Epoch 19/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9990 - loss: 0.0031
Epoch 20/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9992 - loss: 0.0032
Epoch 21/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9990 - loss: 0.0031
Epoch 22/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9986 - loss: 0.0038
Epoch 23/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9996 - loss: 0.0017
Epoch 24/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9992 - loss: 0.0020
Epoch 25/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9998 - loss: 0.0014
Epoch 26/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9994 - loss: 0.0018
Epoch 27/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9994 - loss: 0.0017
Epoch 28/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9998 - loss: 0.0012
Epoch 29/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9994 - loss: 0.0028
Epoch 30/30
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9994 - loss: 0.0022

In [96]:
model_two = tf.keras.models.Sequential([
  tf.keras.layers.Input((X_train.shape[1],)), #  data is already flat hence we do not need to flatten the features trsnalte into an input

  # This is your first hidden layer n 32 neurons
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dropout(0.3),# 20% of your data is left out to lower the chance pof overfittinhs

  # This is your first hidden layer n 16 neurons
  tf.keras.layers.Dense(16, activation='relu'),
  tf.keras.layers.Dropout(0.3),# 20% of your data is left out to lower the chance pof overfittinh
  
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [97]:

model_two.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])

In [ ]:

model_two.fit(X_train, y_train, epochs=10\
    
    
    
    
    \, batch_size=32)

Epoch 1/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 1.0000 - loss: 1.8142e-04
Epoch 2/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.5187e-04
Epoch 3/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 4.9484e-04
Epoch 4/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 2.5430e-04
Epoch 5/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 3.1835e-04
Epoch 6/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 1.0000 - loss: 1.1848e-04
Epoch 7/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.9592e-04
Epoch 8/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9998 - loss: 7.1336e-04
Epoch 9/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 6.7982e-05
Epoch 10/10
154/154 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 1.0000 - loss: 1.3012e-04

In [99]:
probs = model_two.predict(X_test).ravel()

66/66 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step